# Generated by Django 2.1.1 on 2019-06-11 11:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('Subscription', models.IntegerField(choices=[(1, 'Normal'), (2, 'Silver'), (3, 'Gold'), (4, 'Platinium')], default='Normal')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=1000)),
                ('price', models.FloatField()),
            ],
        ),
    ]
