# Generated by Django 2.1.1 on 2019-06-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enamour', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
