# Generated by Django 2.1.4 on 2019-09-14 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enamour', '0002_delete_invoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonDetails',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
