# Generated by Django 2.1.4 on 2019-09-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Enamour', '0003_auto_20190914_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='dateofStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
            ],
        ),
    ]
