# Generated by Django 2.1.4 on 2019-09-17 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enamour', '0004_dateofstock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dateofStock',
        ),
    ]
