# Generated by Django 2.2.2 on 2019-09-18 05:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Enamour', '0005_delete_dateofstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('person_id', models.CharField(blank=True, default=uuid.UUID('bcf7ab26-2377-490d-9c64-0b6622bc069e'), max_length=100, unique=True)),
                ('phone_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email_id', models.EmailField(blank=True, max_length=70)),
            ],
            options={
                'unique_together': {('person_id', 'phone_no')},
            },
        ),
    ]
