# Generated by Django 2.2.2 on 2019-09-18 07:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Enamour', '0006_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Enamour.person')),
                ('months_subscribed', models.IntegerField(max_length=3)),
                ('sub_start_date', models.DateField(blank=True, null=True)),
                ('sub_end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='person_id',
            field=models.CharField(blank=True, default=uuid.UUID('e61ed1f2-c5e4-4322-88bb-173f874c932e'), max_length=100, unique=True),
        ),
    ]
