# Generated by Django 2.2.2 on 2019-09-18 07:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Enamour', '0007_auto_20190918_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_id',
            field=models.CharField(blank=True, default=uuid.UUID('dd136faf-abca-4677-8b96-869fc686602f'), max_length=100, unique=True),
        ),
    ]
