# Generated by Django 2.2.2 on 2019-09-18 08:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Enamour', '0008_auto_20190918_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_id',
            field=models.CharField(blank=True, default=uuid.UUID('b577f78d-5b6b-4608-9404-55b0c1490fd7'), max_length=100, unique=True),
        ),
    ]
