# Generated by Django 2.1.4 on 2019-09-18 09:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Enamour', '0009_auto_20190918_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_id',
            field=models.CharField(blank=True, default=uuid.UUID('44a4eb19-3ae8-4511-ba83-45f1e662abec'), max_length=100, unique=True),
        ),
    ]
