# Generated by Django 2.1.4 on 2019-10-04 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enamour', '0010_auto_20190918_0940'),
    ]

    operations = [
        migrations.DeleteModel(
            name='person',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='pid',
        ),
        migrations.DeleteModel(
            name='subscription',
        ),
    ]
